/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.tamara_vershinina.simple_website;

import io.vertx.core.http.HttpServerResponse;
import io.vertx.core.http.HttpServer;
import io.vertx.ext.web.Router;
import io.vertx.core.Vertx;
import io.vertx.ext.web.handler.StaticHandler;
import io.vertx.ext.web.handler.BodyHandler;
import io.vertx.core.http.HttpServerRequest;

public class App {
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        HttpServer server = vertx.createHttpServer();
        Router router = Router.router(vertx);

       /* router.route().handler(ctx -> {
            // This handler will be called for every request
            HttpServerResponse response = ctx.response();
            response.putHeader("content-type", "text/plain");
            // Write to the response and end it
            response.end("Hello World from Vert.x-Web!");
        });*/
        router.route().handler(BodyHandler.create());
        router.get("/*").handler(StaticHandler.create());
        router.post("/login").handler(ctx -> {
            HttpServerRequest request = ctx.request();
           // System.out.println(request.getFormAttribute("username"));
            if (request.getFormAttribute("username").equals("tom") && request.getFormAttribute("password").equals("gnom")) {
                ctx.redirect("/profile.html");
            }
            else {
                ctx.redirect("/");
            }
        });
        server.requestHandler(router).listen(8080);
    }
}
